### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by Alex-Morskyi** [OleksandrMorskyi/github-crash-course#1]
I think it looks better if the main title is a bit mor orange.

The stylling rule cloud be changed like this:

```css
h1 {
     color: #f0a118;
}
```
