### ISSUE TITLE
Suggedtio; Change title color

### ISSUE THREAD

**Issue by Alex-Morskyi** [OleksandrMorskyi/github-crash-course#1]
i think looks better if the master title is more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #bfb2e8;
}
```
